version: "3.0"

services:
  backend:
    image: behran/goloang
    container_name: rest-api
    ports:
      - "8090:8080"
    volumes:
      - ./src:/go/src/app
    entrypoint: "tail -f /dev/null"
    depends_on:
      - fullstack-postgres          # Uncomment this when using postgres.
    networks:
      - fullstack
  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
  migrate:
    image: migrate/migrate
    networks:
      - fullstack
    volumes:
      - ./src:/go/src/app
    command: ["-path", "migrations", "-database",  "postgresql://admin:secret@full_db_postgres:5432/postgres?sslmode=disable", "up" ]
    links:
      - fullstack-postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped
volumes:
  api:
  database_postgres:                  # Uncomment this when using postgre

networks:
  fullstack:
    driver: bridge
